### ISSUE TITLE
Link error in tutorial example

### ISSUE THREAD

**Issue by pltrzglrb** [scylladb/seastar#662] opened 2019-06-29 18:46 UTC
I am doing the following:

export BOOST_INCLUDEDIR=/home/plrtzglrb/src/boost_1_67_0 (I built boost)
export SEASTAR=/home/plrtzglrb/src/seastar
install-dependencies.sh
g++ (Ubuntu 9.1.0-2ubuntu2~16.04) 9.1.0
configure.py --enable-dpdk --cook fmt --cook c-ares --compiler=g++ --c-compiler=gcc --c++-dialect=gnu++17 --mode="release"

The tutorial example is
```
#include <seastar/core/app-template.hh>
#include <seastar/core/reactor.hh>
#include <iostream>
#include <boost/program_options.hpp>

using namespace seastar;

int main(int argc, char** argv) {

    app_template app;
    app.run(argc, argv, []{
        std::cout << "Hello World\n";
        return make_ready_future<>();
    });

}
```

I run the following to build the code: `g++ getting-started.cc `pkg-config --cflags --libs --static $SEASTAR/build/release/seastar.pc`` 

I get following link error:
```
/usr/bin/ld: /home/localadmin/src/seastar/build/release/_cooking/installed/lib/librte_eal.a(eal_common_devargs.o): in function `rte_devargs_layers_parse':
eal_common_devargs.c:(.text+0x275): undefined reference to `rte_kvargs_parse_delim'
/usr/bin/ld: eal_common_devargs.c:(.text+0x3ed): undefined reference to `rte_kvargs_free'
collect2: error: ld returned 1 exit status
```

can someone help me fix this? I can see all the files are there, include files are there, the .a files also exist.

Thanks!!

**Comment by nyh** [comment] 2019-06-30 09:41
The problem is probably specific to "--enable-dpdk", if you didn't enable that deliberately, it will be easier for you to start without it.
It is not unlikely that after the major overhaul of our build system and how it generates the ".pc" files, the version with DPDK (which is not frequently used) wasn't thoroughly checked and we are putting there libraries in the wrong order, or missing some of them or a necessary "--whole-archive"... Can you please include here the output of
```sh
pkg-config --cflags --libs --static $SEASTAR/build/release/seastar.pc
```
So we can see if something might be wrong there? Thanks.

**Comment by pltrzglrb** [comment] 2019-06-30 18:49
Output from `pkg-config --cflags --libs --static $SEASTAR/build/release/seastar.pc`

```
std=c++17 -U_FORTIFY_SOURCE -Wno-maybe-uninitialized -march=native -fconcepts -DSEASTAR_HAVE_GCC6_CONCEPTS -DSEASTAR_HAVE_DPDK -pthread -I/home/localadmin/src/boost_1_67_0 -I/home/localadmin/src/seastar/build/release/_cooking/installed/include -I/home/localadmin/src/seastar/include -I/home/localadmin/src/seastar/build/release/gen/include -I/usr/include/p11-kit-1 /home/localadmin/src/seastar/build/release/libseastar.a /home/localadmin/src/boost_1_67_0/stage/lib/libboost_program_options.so /home/localadmin/src/boost_1_67_0/stage/lib/libboost_system.so /home/localadmin/src/boost_1_67_0/stage/lib/libboost_thread.so /home/localadmin/src/seastar/build/release/_cooking/installed/lib/libcares.so /usr/lib/libcryptopp.so /home/localadmin/src/seastar/build/release/_cooking/installed/lib/libfmt.a -ldl -lrt /home/localadmin/src/boost_1_67_0/stage/lib/libboost_filesystem.so /home/localadmin/src/boost_1_67_0/stage/lib/libboost_system.so /home/localadmin/src/boost_1_67_0/stage/lib/libboost_thread.so /home/localadmin/src/seastar/build/release/_cooking/installed/lib/librte_cfgfile.a /home/localadmin/src/seastar/build/release/_cooking/installed/lib/librte_cmdline.a /home/localadmin/src/seastar/build/release/_cooking/installed/lib/librte_ethdev.a /home/localadmin/src/seastar/build/release/_cooking/installed/lib/librte_hash.a /home/localadmin/src/seastar/build/release/_cooking/installed/lib/librte_kvargs.a /home/localadmin/src/seastar/build/release/_cooking/installed/lib/librte_mbuf.a /home/localadmin/src/seastar/build/release/_cooking/installed/lib/librte_eal.a /home/localadmin/src/seastar/build/release/_cooking/installed/lib/librte_mempool.a /home/localadmin/src/seastar/build/release/_cooking/installed/lib/librte_mempool_ring.a /home/localadmin/src/seastar/build/release/_cooking/installed/lib/librte_pmd_bnxt.a /home/localadmin/src/seastar/build/release/_cooking/installed/lib/librte_pmd_e1000.a /home/localadmin/src/seastar/build/release/_cooking/installed/lib/librte_pmd_ena.a /home/localadmin/src/seastar/build/release/_cooking/installed/lib/librte_pmd_enic.a /home/localadmin/src/seastar/build/release/_cooking/installed/lib/librte_pmd_fm10k.a /home/localadmin/src/seastar/build/release/_cooking/installed/lib/librte_pmd_qede.a /home/localadmin/src/seastar/build/release/_cooking/installed/lib/librte_pmd_i40e.a /home/localadmin/src/seastar/build/release/_cooking/installed/lib/librte_pmd_ixgbe.a /home/localadmin/src/seastar/build/release/_cooking/installed/lib/librte_pmd_nfp.a /home/localadmin/src/seastar/build/release/_cooking/installed/lib/librte_pmd_ring.a /home/localadmin/src/seastar/build/release/_cooking/installed/lib/librte_pmd_sfc_efx.a /home/localadmin/src/seastar/build/release/_cooking/installed/lib/librte_pmd_vmxnet3_uio.a /home/localadmin/src/seastar/build/release/_cooking/installed/lib/librte_ring.a /home/localadmin/src/seastar/build/release/_cooking/installed/lib/librte_net.a /home/localadmin/src/seastar/build/release/_cooking/installed/lib/librte_timer.a /home/localadmin/src/seastar/build/release/_cooking/installed/lib/librte_pci.a /home/localadmin/src/seastar/build/release/_cooking/installed/lib/librte_bus_pci.a /home/localadmin/src/seastar/build/release/_cooking/installed/lib/librte_bus_vdev.a /usr/lib/x86_64-linux-gnu/libsctp.so /usr/lib/x86_64-linux-gnu/libnuma.so -latomic -lgnutls /usr/lib/x86_64-linux-gnu/libz.so -Wl,-rpath -Wl,/usr/lib/x86_64-linux-gnu -lp11-kit -lgmp -lhogweed -lgmp -lnettle -ltasn1 -lidn -lp11-kit -lz -lprotobuf -pthread -lpthread -lz -lhwloc -lm -lnuma -lltdl -lpthread -ldl -lyaml-cpp -llz4
```

**Comment by pltrzglrb** [comment] 2019-06-30 20:39
I built seastar withith the `--enable-dpdk` flag disabled, I was able to build the tutorial.

**Comment by nyh** [comment] 2019-07-01 08:54
I just committed 44a300cd5064882909c5e64deccd85fb62b7bcf7 by @avikivity which fixes the link order and hopefully solves your problem. Can you please check out the lastest version and try again with "--enable-dpdk" and see if the link problems are solved? Thanks.

**Comment by xiaqunfeng** [comment] 2019-07-01 09:07
can you give me any help about this issue https://github.com/scylladb/seastar/issues/658? @nyh

**Comment by pltrzglrb** [comment] 2019-07-01 17:47
@nyh I was able to build the tutorial example with --enable-dpdk using the master. Thank you!!

**Closed** 2019-07-03 12:32 UTC
