### ISSUE TITLE
Unexpected behavior when using seastar's memory allocation

### ISSUE THREAD

**Issue by LiSu** [scylladb/seastar#801] opened 2020-09-24 07:31 UTC
Hi,

I found that, in the release mode,  calling `malloc(size_t)` doesn't not actually calls `seastar::memory::allocate(size_t)`, whereas calling `operator new` eventually calls `seastar::memory::allocate(size_t)`. While, what I expect is both `malloc(size_t)` and `operator new` will call the `seastar::memory::allocate(size_t)`. 

In the following code, a task is submitted to reactor 1. It calls `malloc(size_t)` and `new` in sequence. The times that `seastar::memory::allocate(size_t)` called before and after each of them are recorded. 

```cpp
int main(int ac, char **av) {
    seastar::app_template app;
    app.run_deprecated(ac, av, [] {
        return seastar::smp::submit_to(1, [] {
            auto before_malloc = seastar::memory::stats().mallocs();
            auto mem_1 = malloc(1024);
            auto after_malloc = seastar::memory::stats().mallocs();
            std::cout << "The first malloc count : " << after_malloc - before_malloc << std::endl;
            free(mem_1);

            auto before_new = seastar::memory::stats().mallocs();
            auto mem_2 = new char[1024];
            auto after_new = seastar::memory::stats().mallocs();
            std::cout << "The second malloc count : " << after_new - before_new << std::endl;
            delete mem_2;
        });
    });
    return 0;
}
```

```cpp
Output:
The first malloc count : 0
The second malloc count : 1
```

As the result shows, calling `malloc(size_t)` does not increases the count, but calling `new` increases the count by 1. I guess the reason is that the `malloc(size_t)` called here is not the `malloc(size_t)` defined in `memory.cc`. But what is the reason behind this?

**Comment by avikivity** [comment] 2020-09-24 15:18
That is very strange and unexpected.

Do you have `using namespaced std;`? perhaps the call was translated to std::malloc.

**Comment by LiSu** [comment] 2020-09-25 06:25
No I don't have `using namespaced std;`. I am using `seastar-19.06-release`, which I suppose shouldn't be a problem.

**Comment by raphaelsc** [comment] 2020-09-25 07:10
also happened to me:

malloc call translates into
  900fae:       8b 5c 24 48             mov    0x48(%rsp),%ebx
  900fb2:       8d 7b 01                lea    0x1(%rbx),%edi
  900fb5:       e8 14 4f 0d 01          callq  19d5ece <__libc_malloc>
  900fba:       48 89 c7                mov    %rax,%rdi
  900fbd:       48 89 44 24 50          mov    %rax,0x50(%rsp)

but we already alias it to malloc, perhaps something changed in newer
gcc versions which broke this

**Comment by avikivity** [comment] 2020-09-25 07:56
I was not able to reproduce. I get

```
The first malloc count : 1
The second malloc count : 1
```

What is your OS version and compiler? What is the compiler command line?

**Comment by LiSu** [comment] 2020-09-25 08:06
OS version: Ubuntu 18.04, 
Compiler: g++8, c++-dialect: gnu++14
Compiler command line: ninja -C build/release

**Comment by avikivity** [comment] 2020-09-25 08:42
What's the command line to build the test program?

**Comment by LiSu** [comment] 2020-09-25 08:45
I built a seastar app under the folder `apps`.
In the `CMakeLists.txt:`

```cpp
seastar_add_app (mem_test
        SOURCES
        main.cc)
```

**Comment by raphaelsc** [comment] 2020-09-28 20:02
found out this is GCC 10 removing dead allocations with optimization -fallocation-dce. this can be fixed by actually using the allocated value.

```
    auto before_malloc = seastar::memory::stats().mallocs();
    auto mem_1 = malloc(1179);
    auto after_malloc = seastar::memory::stats().mallocs();
    std::cout << "The first malloc count : " << after_malloc - before_malloc << std::endl;
    free(mem_1);
```

translates into

```
  8f272e:       41 54                   push   %r12
  8f2730:       55                      push   %rbp
  8f2731:       53                      push   %rbx
  8f2732:       48 83 ec 40             sub    $0x40,%rsp
  8f2736:       48 89 fd                mov    %rdi,%rbp
  8f2739:       48 89 e7                mov    %rsp,%rdi
  8f273c:       e8 2b 1f 0e 01          callq  19d466c <_ZN7seastar6memory5statsEv>
  8f2741:       4c 8b 24 24             mov    (%rsp),%r12
  8f2745:       48 89 e7                mov    %rsp,%rdi
  8f2748:       e8 1f 1f 0e 01          callq  19d466c <_ZN7seastar6memory5statsEv>
  8f274d:       48 8b 1c 24             mov    (%rsp),%rbx
  8f2751:       ba 19 00 00 00          mov    $0x19,%edx
  8f2756:       be 13 ce 21 00          mov    $0x21ce13,%esi
  8f275b:       bf c0 c4 bd 01          mov    $0x1bdc4c0,%edi
```

```
    auto before_malloc = seastar::memory::stats().mallocs();
    auto mem_1 = malloc(1179);
    **assert(mem_1);**
    auto after_malloc = seastar::memory::stats().mallocs();
    std::cout << "The first malloc count : " << after_malloc - before_malloc << std::endl;
    free(mem_1);

```

translates into


```
  8f30f0:       41 54                   push   %r12
  8f30f2:       55                      push   %rbp
  8f30f3:       53                      push   %rbx
  8f30f4:       48 83 ec 48             sub    $0x48,%rsp
  8f30f8:       48 89 fb                mov    %rdi,%rbx
  8f30fb:       48 89 e7                mov    %rsp,%rdi
  8f30fe:       e8 49 17 0e 01          callq  19d484c <_ZN7seastar6memory5statsEv>
  8f3103:       4c 8b 2c 24             mov    (%rsp),%r13
  8f3107:       bf 9b 04 00 00          mov    $0x49b,%edi
  **8f310c:       e8 0d 23 0e 01          callq  19d541e <__libc_malloc>**
  8f3111:       48 85 c0                test   %rax,%rax
  8f3114:       0f 84 8f 00 00 00       je     8f31a9 <_ZN12key_to_shard13run_test_caseEv+0xbb>
  8f311a:       49 89 c4                mov    %rax,%r12
  8f311d:       48 89 e7                mov    %rsp,%rdi
  8f3120:       e8 27 17 0e 01          callq  19d484c <_ZN7seastar6memory5statsEv>
  8f3125:       48 8b 2c 24             mov    (%rsp),%rbp
```

**Comment by avikivity** [comment] 2020-09-29 10:27
Nice. Closing as invalid.

**Comment by avikivity** [comment] 2020-09-29 10:27
Too bad it isn't eliminating the new call.

**Closed by avikivity** 2020-09-29 10:27 UTC
