### ISSUE TITLE
If collectd is not started prometheus metrics are labeled as 'locahost' instead of host name they are comming from

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/seastar#233] opened 2017-01-08 13:35 UTC

**Comment by amnonh** [comment] 2017-01-08 13:49
@slivne please assign to me

**Closed** 2017-01-08 14:54 UTC

**Comment by amnonh** [comment] 2017-01-08 14:55
The issue is relevent to version 1.4, 1.5 and 1.6

**Comment by avikivity** [comment] 2017-01-08 15:14
seastar doesn't have versions 1.4, 1.5, or 1.6.

**Comment by tgrabiec** [comment] 2017-01-09 13:55
Dup of scylladb/scylla#1989
