### ISSUE TITLE
cmake should check for `sys/sdt.h` offered by `systemtap-sdt-dev`

### ISSUE THREAD

**Issue by tchaikov** [scylladb/seastar#557] opened 2018-12-16 15:42 UTC
otherwise `make` could fail like

```
/var/ceph/ceph-ubuntu-16.04-kefu/src/seastar/src/core/reactor.cc:100:10: fatal error: sys/sdt.h: No such file or directory
 #include <sys/sdt.h>
          ^~~~~~~~~~~
compilation terminated.
CMakeFiles/seastar.dir/build.make:412: recipe for target 'CMakeFiles/seastar.dir/src/core/reactor.cc.o' failed
make[2]: *** [CMakeFiles/seastar.dir/src/core/reactor.cc.o] Error 1
```

**Comment by hakuch** [comment] 2018-12-17 15:19
This a duplicate of #223.

**Comment by tchaikov** [comment] 2018-12-17 15:36
if it's a dup, am i supposed to close it?

but IMHO, #223 is different from this issue: #223 suggests that it's a bug in seastar. while this issue suggests that we need to update cmake script to detect the used package.

**Comment by hakuch** [comment] 2018-12-17 15:47
@tchaikov, on second thought I agree that it's not a duplicate. I think the main "topic" of the issue is that the dependency should be checked at configure-time (note that it's already listed as a dependency in `install-dependencies.sh`).

**Comment by hakuch** [comment] 2018-12-17 15:53
I will prepare a patch that adds a check in `CMakeLists.txt` and an "ingredient".

**Closed** 2023-09-10 14:45 UTC
