### ISSUE TITLE
Failed to compile on ubuntu 16.04 gcc 5.4.0 boost 1.58

### ISSUE THREAD

**Issue by ahabalmefager** [scylladb/seastar#338] opened 2017-09-11 14:16 UTC
Here's the output

FAILED: g++-5 -MD -MT build/release/net/tls.o -MF build/release/net/tls.o.d -O2 -I/home/itsik/tools/seastar/build/release/gen -I/home/itsik/tools/seastar/build/release/c-ares -std=gnu++1y -g  -Wall -Werror -Wno-error=deprecated-declarations -fvisibility=hidden  -pthread -I/home/itsik/tools/seastar -U_FORTIFY_SOURCE  -I/home/itsik/tools/seastar/fmt -DBOOST_TEST_DYN_LINK -Wno-overloaded-virtual -Wno-maybe-uninitialized -DFMT_HEADER_ONLY -DHAVE_HWLOC -DHAVE_NUMA -DHAVE_LZ4_COMPRESS_DEFAULT -c -o build/release/net/tls.o net/tls.cc
In file included from /home/itsik/tools/seastar/core/seastar.hh:45:0,
                 from /home/itsik/tools/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/home/itsik/tools/seastar/core/future.hh: In instantiation of ‘void seastar::future_state<T>::set(A&& ...) [with A = {std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> >}; T = {seastar::connected_socket}]’:
/home/itsik/tools/seastar/core/future.hh:705:9:   required from ‘seastar::future<T>::future(seastar::ready_future_marker, A&& ...) [with A = {std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> >}; T = {seastar::connected_socket}]’
/home/itsik/tools/seastar/core/future.hh:1197:73:   required from ‘seastar::future<T ...> seastar::make_ready_future(A&& ...) [with T = {seastar::connected_socket}; A = {std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> >}]’
net/tls.cc:1165:108:   required from here
/home/itsik/tools/seastar/core/future.hh:210:9: error: no matching function for call to ‘std::tuple<seastar::connected_socket>::tuple(std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> >)’
         new (&_u.value) std::tuple<T...>(std::forward<A>(a)...);
         ^
In file included from /usr/include/c++/5/unordered_map:41:0,
                 from /home/itsik/tools/seastar/core/sstring.hh:29,
                 from /home/itsik/tools/seastar/core/seastar.hh:44,
                 from /home/itsik/tools/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/usr/include/c++/5/tuple:538:2: note: candidate: template<class _Alloc, class ... _UElements, class> std::tuple< <template-parameter-1-1> >::tuple(std::allocator_arg_t, const _Alloc&, std::tuple<_Args2 ...>&&)
  tuple(allocator_arg_t __tag, const _Alloc& __a,
  ^
/usr/include/c++/5/tuple:538:2: note:   template argument deduction/substitution failed:
In file included from /home/itsik/tools/seastar/core/seastar.hh:45:0,
                 from /home/itsik/tools/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/home/itsik/tools/seastar/core/future.hh:210:9: note:   cannot convert ‘std::forward<std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> > >((* & a#0))’ (type ‘std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> >’) to type ‘std::allocator_arg_t’
         new (&_u.value) std::tuple<T...>(std::forward<A>(a)...);
         ^
In file included from /usr/include/c++/5/unordered_map:41:0,
                 from /home/itsik/tools/seastar/core/sstring.hh:29,
                 from /home/itsik/tools/seastar/core/seastar.hh:44,
                 from /home/itsik/tools/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/usr/include/c++/5/tuple:529:2: note: candidate: template<class _Alloc, class ... _UElements, class> std::tuple< <template-parameter-1-1> >::tuple(std::allocator_arg_t, const _Alloc&, const std::tuple<_Args2 ...>&)
  tuple(allocator_arg_t __tag, const _Alloc& __a,
  ^
/usr/include/c++/5/tuple:529:2: note:   template argument deduction/substitution failed:
In file included from /home/itsik/tools/seastar/core/seastar.hh:45:0,
                 from /home/itsik/tools/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/home/itsik/tools/seastar/core/future.hh:210:9: note:   cannot convert ‘std::forward<std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> > >((* & a#0))’ (type ‘std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> >’) to type ‘std::allocator_arg_t’
         new (&_u.value) std::tuple<T...>(std::forward<A>(a)...);
         ^
In file included from /usr/include/c++/5/unordered_map:41:0,
                 from /home/itsik/tools/seastar/core/sstring.hh:29,
                 from /home/itsik/tools/seastar/core/seastar.hh:44,
                 from /home/itsik/tools/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/usr/include/c++/5/tuple:523:2: note: candidate: template<class _Alloc> std::tuple< <template-parameter-1-1> >::tuple(std::allocator_arg_t, const _Alloc&, std::tuple< <template-parameter-1-1> >&&)
  tuple(allocator_arg_t __tag, const _Alloc& __a, tuple&& __in)
  ^
/usr/include/c++/5/tuple:523:2: note:   template argument deduction/substitution failed:
In file included from /home/itsik/tools/seastar/core/seastar.hh:45:0,
                 from /home/itsik/tools/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/home/itsik/tools/seastar/core/future.hh:210:9: note:   cannot convert ‘std::forward<std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> > >((* & a#0))’ (type ‘std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> >’) to type ‘std::allocator_arg_t’
         new (&_u.value) std::tuple<T...>(std::forward<A>(a)...);
         ^
In file included from /usr/include/c++/5/unordered_map:41:0,
                 from /home/itsik/tools/seastar/core/sstring.hh:29,
                 from /home/itsik/tools/seastar/core/seastar.hh:44,
                 from /home/itsik/tools/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/usr/include/c++/5/tuple:519:2: note: candidate: template<class _Alloc> std::tuple< <template-parameter-1-1> >::tuple(std::allocator_arg_t, const _Alloc&, const std::tuple< <template-parameter-1-1> >&)
  tuple(allocator_arg_t __tag, const _Alloc& __a, const tuple& __in)
  ^
/usr/include/c++/5/tuple:519:2: note:   template argument deduction/substitution failed:
In file included from /home/itsik/tools/seastar/core/seastar.hh:45:0,
                 from /home/itsik/tools/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/home/itsik/tools/seastar/core/future.hh:210:9: note:   cannot convert ‘std::forward<std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> > >((* & a#0))’ (type ‘std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> >’) to type ‘std::allocator_arg_t’
         new (&_u.value) std::tuple<T...>(std::forward<A>(a)...);
         ^
In file included from /usr/include/c++/5/unordered_map:41:0,
                 from /home/itsik/tools/seastar/core/sstring.hh:29,
                 from /home/itsik/tools/seastar/core/seastar.hh:44,
                 from /home/itsik/tools/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/usr/include/c++/5/tuple:513:2: note: candidate: template<class _Alloc, class ... _UElements, class> std::tuple< <template-parameter-1-1> >::tuple(std::allocator_arg_t, const _Alloc&, _UElements&& ...)
  tuple(allocator_arg_t __tag, const _Alloc& __a,
  ^
/usr/include/c++/5/tuple:513:2: note:   template argument deduction/substitution failed:
In file included from /home/itsik/tools/seastar/core/seastar.hh:45:0,
                 from /home/itsik/tools/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/home/itsik/tools/seastar/core/future.hh:210:9: note:   cannot convert ‘std::forward<std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> > >((* & a#0))’ (type ‘std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> >’) to type ‘std::allocator_arg_t’
         new (&_u.value) std::tuple<T...>(std::forward<A>(a)...);
         ^
In file included from /usr/include/c++/5/unordered_map:41:0,
                 from /home/itsik/tools/seastar/core/sstring.hh:29,
                 from /home/itsik/tools/seastar/core/seastar.hh:44,
                 from /home/itsik/tools/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/usr/include/c++/5/tuple:506:2: note: candidate: template<class _Alloc> std::tuple< <template-parameter-1-1> >::tuple(std::allocator_arg_t, const _Alloc&, const _Elements& ...)
  tuple(allocator_arg_t __tag, const _Alloc& __a,
  ^
/usr/include/c++/5/tuple:506:2: note:   template argument deduction/substitution failed:
In file included from /home/itsik/tools/seastar/core/seastar.hh:45:0,
                 from /home/itsik/tools/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/home/itsik/tools/seastar/core/future.hh:210:9: note:   cannot convert ‘std::forward<std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> > >((* & a#0))’ (type ‘std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> >’) to type ‘std::allocator_arg_t’
         new (&_u.value) std::tuple<T...>(std::forward<A>(a)...);
         ^
In file included from /usr/include/c++/5/unordered_map:41:0,
                 from /home/itsik/tools/seastar/core/sstring.hh:29,
                 from /home/itsik/tools/seastar/core/seastar.hh:44,
                 from /home/itsik/tools/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/usr/include/c++/5/tuple:502:2: note: candidate: template<class _Alloc> std::tuple< <template-parameter-1-1> >::tuple(std::allocator_arg_t, const _Alloc&)
  tuple(allocator_arg_t __tag, const _Alloc& __a)
  ^
/usr/include/c++/5/tuple:502:2: note:   template argument deduction/substitution failed:
In file included from /home/itsik/tools/seastar/core/seastar.hh:45:0,
                 from /home/itsik/tools/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/home/itsik/tools/seastar/core/future.hh:210:9: note:   cannot convert ‘std::forward<std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> > >((* & a#0))’ (type ‘std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> >’) to type ‘std::allocator_arg_t’
         new (&_u.value) std::tuple<T...>(std::forward<A>(a)...);
         ^
In file included from /usr/include/c++/5/unordered_map:41:0,
                 from /home/itsik/tools/seastar/core/sstring.hh:29,
                 from /home/itsik/tools/seastar/core/seastar.hh:44,
                 from /home/itsik/tools/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/usr/include/c++/5/tuple:496:19: note: candidate: template<class ... _UElements, class> constexpr std::tuple< <template-parameter-1-1> >::tuple(std::tuple<_Args1 ...>&&)
         constexpr tuple(tuple<_UElements...>&& __in)
                   ^
/usr/include/c++/5/tuple:496:19: note:   template argument deduction/substitution failed:
In file included from /home/itsik/tools/seastar/core/seastar.hh:45:0,
                 from /home/itsik/tools/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/home/itsik/tools/seastar/core/future.hh:210:9: note:   ‘std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> >’ is not derived from ‘std::tuple<_Elements ...>’
         new (&_u.value) std::tuple<T...>(std::forward<A>(a)...);
         ^
In file included from /usr/include/c++/5/unordered_map:41:0,
                 from /home/itsik/tools/seastar/core/sstring.hh:29,
                 from /home/itsik/tools/seastar/core/seastar.hh:44,
                 from /home/itsik/tools/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/usr/include/c++/5/tuple:489:19: note: candidate: template<class ... _UElements, class> constexpr std::tuple< <template-parameter-1-1> >::tuple(const std::tuple<_Args1 ...>&)
         constexpr tuple(const tuple<_UElements...>& __in)
                   ^
/usr/include/c++/5/tuple:489:19: note:   template argument deduction/substitution failed:
In file included from /home/itsik/tools/seastar/core/seastar.hh:45:0,
                 from /home/itsik/tools/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/home/itsik/tools/seastar/core/future.hh:210:9: note:   ‘std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> >’ is not derived from ‘const std::tuple<_Elements ...>’
         new (&_u.value) std::tuple<T...>(std::forward<A>(a)...);
         ^
In file included from /usr/include/c++/5/unordered_map:41:0,
                 from /home/itsik/tools/seastar/core/sstring.hh:29,
                 from /home/itsik/tools/seastar/core/seastar.hh:44,
                 from /home/itsik/tools/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/usr/include/c++/5/tuple:484:17: note: candidate: constexpr std::tuple< <template-parameter-1-1> >::tuple(std::tuple< <template-parameter-1-1> >&&) [with _Elements = {seastar::connected_socket}]
       constexpr tuple(tuple&&) = default; 
                 ^
/usr/include/c++/5/tuple:484:17: note:   no known conversion for argument 1 from ‘std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> >’ to ‘std::tuple<seastar::connected_socket>&&’
/usr/include/c++/5/tuple:479:19: note: candidate: template<class ... _UElements, class> constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...)
         constexpr tuple(_UElements&&... __elements)
                   ^
/usr/include/c++/5/tuple:479:19: note:   template argument deduction/substitution failed:
/usr/include/c++/5/tuple:475:40: error: no type named ‘type’ in ‘struct std::enable_if<false, void>’
       template<typename... _UElements, typename = typename
                                        ^
/usr/include/c++/5/tuple:472:17: note: candidate: constexpr std::tuple< <template-parameter-1-1> >::tuple(const _Elements& ...) [with _Elements = {seastar::connected_socket}]
       constexpr tuple(const _Elements&... __elements)
                 ^
/usr/include/c++/5/tuple:472:17: note:   no known conversion for argument 1 from ‘std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> >’ to ‘const seastar::connected_socket&’
/usr/include/c++/5/tuple:468:17: note: candidate: constexpr std::tuple< <template-parameter-1-1> >::tuple() [with _Elements = {seastar::connected_socket}]
       constexpr tuple()
                 ^
/usr/include/c++/5/tuple:468:17: note:   candidate expects 0 arguments, 1 provided
[81/352] CXX build/release/tests/fstream_test.o
ninja: build stopped: subcommand failed.

**Comment by rayqi36** [comment] 2017-09-14 05:35
I have the same problem on Ubuntu 16.04

**Comment by argenet** [comment] 2017-09-24 23:46
It seems that gcc cannot automatically upcast unique_ptr<tls_connected_socket_impl> to unique_ptr<connected_socket> because tls_connected_socket_impl has two public bases so this cast is ambiguous:
https://stackoverflow.com/questions/36401999/is-unique-ptrderived-to-unique-ptrbase-up-casting-automatic

The proper fix would be to either explicitly cast the unique_ptr before passing it to make_ready_future or re-arrange tls_connected_socket_impl to only derive from connected_socket and not from session::session_ref. The first one seems easier to do but the latter looks better as multiple public inheritance in C++ is rarely a good idea.

By the way, this compiles fine with GCC 7.2. Not sure if this is a GCC 7.x bug or they have relaxed corresponding checks.

**Comment by argenet** [comment] 2017-09-25 03:27
The following simplified example reproduces the issue.

`#include <memory>
#include <tuple>

struct A
{
    A() {}
};

struct WrapperA
{
    explicit WrapperA(std::unique_ptr<A> a)
        : _a(std::move(a))
    {}

private:
    std::unique_ptr<A> _a;
};

struct C : A
{
};

template <class... T>
struct Holder
{
    template <class... A>
    auto set(A&&... a)
    {
        std::tuple<T...> t(std::forward<A>(a)...);
        return sizeof...(A);
    }
};

int main()
{
    Holder<WrapperA> h{};
    return h.set(std::make_unique<C>());
}
`
Note that it only fails with GCC 5.4 or earlier. GCC 6.x and 7.x compile this fine.
Also, Clang compiles this starting with v3.5.1:
https://godbolt.org/g/PwyHnH

So far looks like a bug that has been fixed in latter compiler versions.

**Closed** 2017-09-28 19:56 UTC

**Comment by Ericaust** [comment] 2018-07-21 22:37
Mine also failed on ubuntu 16.04 with GCC 7. Any ways to solve this issue?
![image](https://user-images.githubusercontent.com/23627676/43040571-ffbda94e-8cfb-11e8-9f38-3982281dde65.png)
