### ISSUE TITLE
Disable errors on unrecognised options in `app_template`

### ISSUE THREAD

**Issue by Fikafusik** [scylladb/seastar#1153] opened 2022-07-22 14:25 UTC
I am trying to run Catch2 inside `app_template`. When passing Catch2 parameters inside `app_template` I get an error
`error: unrecognised option '--success'`.
Therefore, I have to register all Catch2 parameters in advance, which looks ugly:
```cpp
using suppress_unrecognised_option_error = std::string;
app.add_options()
    ("help", "see Catch2's --help")
    ("success", "see Catch2's --success")
    ("break", "see Catch2's --break")
    ("nothrow", "see Catch2's --nothrow")
    ("invisibles", "see Catch2's --invisibles")
    ("out", bpo::value<suppress_unrecognised_option_error>(), "see Catch2's --out <filename>")
    ("reporter", bpo::value<suppress_unrecognised_option_error>(), "see Catch2's --reporter <name[::key=value]*>")
    // many more parameters...
;
```
It would be nice to be able to disable checking for unrecognized parameters. In this case, it's safe because Catch2 does the same check.

**Comment by denesb** [comment] 2022-07-25 04:53
In the future please send questions to the seastar-dev@googlegroups.com mailing list.
If you want to forward all parameters to your application anyway, you can just not pass `argv` and `argc` to app_template. But even better, you can do something like what we do when we run boost tests. We pass all command line arguments to boost, but if the command-line contains a `--` string, everything after that is forwarded to seastar. `boost::test` seems to do this automatically -- it strips everything before `--` and passes the rest to user-code. You can implement this very easily with pointer arithmetics yourself.

**Comment by denesb** [comment] 2022-07-25 05:22
Closing, because this is not a bug in seastar. Raising errors on unrecognized command line arguments is intentional and the application is expected to take care of removing any options not recognized by seastar from the `argv`.

**Closed by denesb** 2022-07-25 05:22 UTC
