### ISSUE TITLE
reactor may spin for a long time in flush_pending_io() for slow disks

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/seastar#538] opened 2018-11-27 01:56 UTC
HEAD: 987d04ede0d4def1c092495954e31187b1bd3490

*Description*

Currently we have the following code in reactor.cc:

```
reactor::flush_pending_aio() {
    for (auto& ioq : my_io_queues) {
        ioq->poll_io_queue();
    }

    bool did_work = false;
    while (!_pending_aio.empty()) {
        auto nr = _pending_aio.size();
        auto iocbs = _pending_aio.data();
        auto r = io_submit(_io_context, nr, iocbs);
        size_t nr_consumed;
        if (r == -1) {
            nr_consumed = handle_aio_error(iocbs[0], errno);
        } else {
            nr_consumed = size_t(r);
        }

        did_work = true;
        if (nr_consumed == nr) {
            _pending_aio.clear();
        } else {
            _pending_aio.erase(_pending_aio.begin(), _pending_aio.begin() + nr_consumed);
        }
    }
```

...and

```
size_t
reactor::handle_aio_error(::iocb* iocb, int ec) {
    switch (ec) {
        case EINVAL:
        case EOPNOTSUPP:
            aio_nowait_supported = false;
            set_nowait(*iocb, false);
            return 0;
        case EAGAIN:
            return 0;
        case EBADF: {
            auto desc = reinterpret_cast<io_desc*>(get_user_data(*iocb));
            _free_iocbs.push(iocb);
            try {
                throw std::system_error(EBADF, std::system_category());
            } catch (...) {
                desc->set_exception(std::current_exception());
            }
            desc->notify_requests_finished();
            delete desc;
            // if EBADF, it means that the first request has a bad fd, so
            // we will only remove it from _pending_aio and try again.
            return 1;
        }
        default:
            ++_io_stats.aio_errors;
            throw_system_error_on(true, "io_submit");
            abort();
    }
}
```

If disk is slow and `io_submit` returns -1 and sets `errno` to `EAGAIN` then we will spin in this loop until resources are released because `static_vector.erase(it,it)` is a no-op.

**Comment by vladzcloudius** [comment] 2018-11-27 15:10
@glommer This issue is about the *possibility* for a spinning just as stated in the opening message. I didn't claim in this issue that I'm able to reproduce it. 

I assume you have the scylladb/scylla#3941 in mind here. I suggest we switch the discussion there.

**Comment by avikivity** [comment] 2018-11-27 15:17
EAGAIN has nothing to do with slow disks. It has to do with exceeding the maximum number of active iocbs, and this should never happen since we set tha aio_max_nr sysctl. We could back off and wait for the next poll period, but I don't think this is a likely error.

**Comment by vladzcloudius** [comment] 2018-11-27 15:42
@avikivity Well, even in this case for a slow disk there is a higher chance to hit this limit however I see that our code won't let it happen.  However...

I'm afraid you may miss another possibility for io_submit() to return EAGAIN and this is when a kernel fails to allocate memory. 

In this case you would expect to get ENOMEM but io_submit() would still return EAGAIN.

See an RFC with a fix and a discussion about it here: https://markmail.org/thread/75iupwaiedop6smt
Apparently this patch still hasn't been applied: https://elixir.bootlin.com/linux/v4.20-rc4/source/fs/aio.c#L1804

Maybe this is a likely error, maybe not - IMO we should not leave such holes in the code especially when it's so easy to fix.

**Comment by avikivity** [comment] 2019-05-18 16:21
Closing until the problem is observed in the wild. ENOMEM during aio is very unlikely, and if the kernel runs out of memory, spinning in aio is going to be the least of our concerns. The application is likely to be oom-killed soon.

**Closed by avikivity** 2019-05-18 16:21 UTC
