### ISSUE TITLE
Tutorial link broken

### ISSUE THREAD

**Issue by alecco** [scylladb/seastar#780] opened 2020-08-10 16:52 UTC
[Docs homepage tutorial link is broken](http://docs.seastar.io/master/index.html)

[source seastar.hh Doxygen comment](https://github.com/scylladb/seastar/blob/master/include/seastar/core/seastar.hh#L30)

**Comment by nyh** [comment] 2020-08-11 07:02
Also noted earlier by @dekimir.
@avikivity explained that the docs site is generated by building Seastar and copying `build/release/doc/html/*` to the site.
However, `ninja -C build/release doc/docs` creates `build/release/doc/tutorial.html` - it's not in the html/ directory so it doesn't get copied.
The fix can be as simple as changing `doc/CMakeLists.txt` to put the output in html/tutorial.html, instead of tutorial.html.
However I don't understand how and when this got broken - it used to work... So what changed?

**Comment by alecco** [comment] 2020-10-07 20:56
Sorry, but the links still 404.

http://docs.seastar.io/master/index.html

http://docs.seastar.io/master/tutorial.html
http://docs.seastar.io/master/split/

**Comment by nyh** [comment] 2020-10-07 21:52
Yes, I noted this on the mailing list and forgot to update here.

It appears that https://jenkins.scylladb.com/job/seastar/job/seastar-build/compiler=g++,label_exp=seastar/lastBuild/console
has been failing for the last year and 7 months (!).

I could still manually run the seastar-docwriter job, and now http://docs.seastar.io/master/index.html has the new tutorial and multi-page version lines which Kefu added, but the files do not actually exist :-(

Can anyone familiar with this Jenkins setup (@avikivity ? @penberg ?) please help me figure out what isn't happening like it should?
Thanks.

**Comment by avikivity** [comment] 2020-10-08 09:32
@nyh what's broken? is docwriter not copying all files it should? if you point me to which files are missing, I can fix that.

**Comment by nyh** [comment] 2020-10-08 13:54
@avikivity I'm not familiar with all the Jenkins jobs and how exactly they depend on each other, but it seemed to me from my brief analysis that the "docwriter" job works correctly - and this is why in http://docs.seastar.io/master/index.html we have now the updated links (modified in a recent commit) - but the "docwriter" job doesn't actually build anything, it depends on a build job which itself fails to build and has been failing for more than a year (see comment above) so it simply copies whatever files were generated long ago. At least it seems to me that this is what happens, but maybe I'm misunderstanding what I'm seeing. I was hoping that you or @penberg are more familiar with the dependencies of these Jenkins jobs and can find what exactly went wrong.

**Comment by avikivity** [comment] 2020-10-11 08:16
No, docwriter builds the documentation itself.

**Comment by nyh** [comment] 2020-10-11 08:40
@avikivity what I saw is that https://jenkins.scylladb.com/job/seastar/job/seastar-docwriter/ lists as "upstream" https://jenkins.scylladb.com/job/seastar/job/seastar-build/ and that specifies as "default" configuration https://jenkins.scylladb.com/job/seastar/job/seastar-build/compiler=g++,label_exp=seastar/
The last one fails. I assumed this breaks also the first one, which relies on the last one. If it doesn't, then I don't understand what is actually wrong.

**Comment by nyh** [comment] 2020-10-11 08:45
@avikivity looking at https://jenkins.scylladb.com/job/seastar/job/seastar-docwriter/2127/consoleFull, it seems maybe the problem is that "docwriter" runs "ninja -C build/release doc_api" while it should have been "docs", not just "doc_api" ?

**Comment by avikivity** [comment] 2020-10-11 16:25
I can change it and see

**Comment by avikivity** [comment] 2020-10-11 17:05
After much trial-and-error installing the texlive dependencies, I get

```
FAILED: doc/tutorial.pdf 
cd /home/avi/seastar/build/release/doc && /home/avi/seastar/doc/md2pdf /home/avi/seastar/doc/tutorial.md /home/avi/seastar/build/release/doc/tutorial.pdf
Error producing PDF.
! pdfTeX error (font expansion): auto expansion is only possible with scalable 
fonts.
\AtBegShi@Output ...ipout \box \AtBeginShipoutBox 
                                                  \fi \fi 
l.179 

```

**Comment by avikivity** [comment] 2020-10-11 17:07
Maybe the change of transformations is too short, and we need a conversion to EBCDIC and to SGML somewhere in the pipeline.

**Comment by nyh** [comment] 2020-10-11 19:02
> After much trial-and-error installing the texlive dependencies, I get
> 
> ```
> FAILED: doc/tutorial.pdf 
> cd /home/avi/seastar/build/release/doc && /home/avi/seastar/doc/md2pdf /home/avi/seastar/doc/tutorial.md /home/avi/seastar/build/release/doc/tutorial.pdf
> Error producing PDF.
> ! pdfTeX error (font expansion): auto expansion is only possible with scalable 
> fonts.
> \AtBegShi@Output ...ipout \box \AtBeginShipoutBox 
>                                                   \fi \fi 
> l.179 
> ```

TeX is only needed for the PDF version, which we don't link on docs.seastar.io - maybe we should, but we don't, so I guess it's not criticial to get this part to work now.
In doc/CMakeLists.tx we have:
```
add_custom_target (docs
  DEPENDS
    doc_api
    doc_tutorial_html
    doc_tutorial_html_split
    doc_tutorial_pdf)
```
So if you don't want the entire "docs", you can just build  doc_api doc_tutorial_html  doc_tutorial_html_split

Maybe it will be nice to get the PDF working eventually, but really not urgent.

**Comment by nyh** [comment] 2020-10-12 20:27
@avikivity apparently I don't have write permissions to https://jenkins.scylladb.com/job/seastar/job/seastar-docwriter/ - I don't know who has them besides you.
Can you please change the line that has:
```
dockrun ninja -C build/release docs
```
To
```
dockrun ninja -C build/release doc_api doc_tutorial_html doc_tutorial_html_split
```
I see in the logs the same PDF generation errors that you got, so we can just skip it for now...
Thanks.

**Comment by nyh** [comment] 2020-10-13 08:08
Excellent. It seems the links are good now. So closing this issue again.

**Closed by nyh** 2020-10-13 08:08 UTC
