### ISSUE TITLE
undefined reference to `seastar::internal::future_base::set_coroutine(seastar::task&)'

### ISSUE THREAD

**Issue by jeffRTC** [scylladb/seastar#942] opened 2021-09-08 20:43 UTC
I'm getting bunch of undefined reference errors when compiling an app that uses your coroutines. My compiler is G++ and it's version is  11.0.1 20210417.

```
/usr/bin/ld: /tmp/ccdafXqN.o: in function `void seastar::internal::awaiter<seastar::accept_result>::await_suspend<seastar::internal::coroutine_traits_base<void>::promise_type>(std::__n4861::coroutine_handle<seastar::internal::coroutine_traits_base<void>::promise_type>)':
/home/ProxyServer/seastar/include/seastar/core/coroutine.hh:156: undefined reference to `seastar::internal::future_base::set_coroutine(seastar::task&)'
/usr/bin/ld: /tmp/ccdafXqN.o: in function `void seastar::internal::awaiter<void>::await_suspend<seastar::internal::coroutine_traits_base<void>::promise_type>(std::__n4861::coroutine_handle<seastar::internal::coroutine_traits_base<void>::promise_type>)':
/home/ProxyServer/seastar/include/seastar/core/coroutine.hh:156: undefined reference to `seastar::internal::future_base::set_coroutine(seastar::task&)'
```

I compile with C++20 enabled. 

```
#include <iostream>
#include <string>

#include <seastar/util/std-compat.hh>

#ifndef SEASTAR_COROUTINES_ENABLED

int main(int argc, char** argv) {
    std::cout << "coroutines not available\n";
    return 0;
}

#else


#include <seastar/core/app-template.hh>
#include <seastar/core/coroutine.hh>
#include <seastar/core/seastar.hh>
#include <seastar/core/loop.hh>
#include <seastar/core/reactor.hh>
#include <seastar/core/future-util.hh>
#include <seastar/net/api.hh>

const char* canned_response = "HTTP/1.1 200 OK\r\nContent-Length: 13\r\nConnection: close\r\n\r\nHello, world!";

seastar::future<> service_loop() {
    seastar::listen_options lo;

    // This will allow us to re run the app without port binding errors
    lo.reuse_address = true;

    auto listener = seastar::listen(seastar::make_ipv4_address({1234}), lo);

    while(true) {
        seastar::accept_result session = co_await listener.accept();

        seastar::connected_socket socket = std::move(session.connection);
        seastar::socket_address peer = session.remote_address;

        std::cout << "Received a Connection from " << peer << "\n";

        auto out = socket.output();

        co_await out.write(canned_response);
        co_await out.close();
    }
}

int main(int argc, char** argv) {
    // Give the ability to kill the program
    seastar::app_template::config config;
    config.auto_handle_sigint_sigterm = false;

    seastar::app_template app{config};

    app.run(argc, argv, [] () -> seastar::future<> {
        seastar::parallel_for_each(boost::irange<unsigned>(0, seastar::smp::count),
                [] (unsigned i) -> seastar::future<> {
            co_await seastar::smp::submit_to(i, service_loop);
        });
    });
}

#endif

```

**Comment by jeffRTC** [comment] 2021-09-08 22:39
@avikivity
@nyh


Just to be clear, I've attempted compile your coroutine demo too but it fails the same way. Tried Clang and same error.

**Comment by Rjerk** [comment] 2021-09-09 06:53
I solved this by adding extra flags for the cpp compiler if you need coroutines `--cflags="-fcoroutines"`:

```
./configure.py --mode=release --prefix=/usr/local --c++-dialect=gnu++20 --without-tests --cflags="-fcoroutines"
```

**Comment by nyh** [comment] 2021-09-09 07:01
If I understand correctly (but please correct me if I'm wrong), only g++ needs this "-fcoroutines" flag to support coroutines - clang (10 and above) doesn't need any special flag to support it. @jeffRTC you said you also had this problem on clang - could you be using an older version of clang?

But obviously, the whole point of having a `configure.py` is that it should figure out on its own whether "-fcoroutines" is needed or not, without having the user to be responsible for this choice. A patch to do that would be welcome.

**Comment by avikivity** [comment] 2021-09-09 08:47
I don't think Seastar should enable an experimental feature unconditionally.

**Comment by nyh** [comment] 2021-09-09 09:13
> I don't think Seastar should enable an experimental feature unconditionally.

Nobody can guess that we enable it unconditionally with clang, but not with g++. If that's what you think is the right behavior, it should at least be documented in `README.md`.  We already have a bunch of coroutine stuff in `tutorial.md` (and of course in the doxygen), and I don't think we explain anywhere that coroutines are more stable in clang and more experimental (i.e., buggy?) in g++, why, and how to enable them. I think we need to explain the situation (and how to build) better in README.md.

**Comment by jeffRTC** [comment] 2021-09-09 13:31
> If I understand correctly (but please correct me if I'm wrong), only g++ needs this "-fcoroutines" flag to support coroutines - clang (10 and above) doesn't need any special flag to support it. @jeffRTC you said you also had this problem on clang - could you be using an older version of clang?
> 
> But obviously, the whole point of having a `configure.py` is that it should figure out on its own whether "-fcoroutines" is needed or not, without having the user to be responsible for this choice. A patch to do that would be welcome.

g++ by default on newer versions enable coroutines when compiled with C++20 and it doesn't even understand -fcoroutines flag.


clang requires that flag. I'm using newer clang version.

**Comment by jeffRTC** [comment] 2021-09-09 13:37
https://www.phoronix.com/scan.php?page=news_item&px=GCC-11-Flips-On-CPP20-Coroutine

**Comment by jeffRTC** [comment] 2021-09-09 13:38
clang needs -fcoroutines-ts flag

**Comment by jeffRTC** [comment] 2021-09-09 14:16
Rebuilding seastar with C++20 flag worked

**Comment by nyh** [comment] 2021-09-12 09:38
I'm closing this issue as a duplicate of #943 (for which I already sent a patch for review). Your problem was that you compiled the Seastar library with C++17 (because that's what configure.py chose by default...) but then tried to use it in C++20. In general, code that uses Seastar should use the same compilation flags as Seastar, which is why we have them in `seastar.pc`.

The "-fcoroutines" issue - that it needs to be documented because it's not obvious at all - is a separate issue (which we should open), but I believe not related to the specific link error in the top of this issue.

**Closed by nyh** 2021-09-12 09:38 UTC
