### ISSUE TITLE
demo/tcp_sctp_client_demo.cc calculate "Total Time" error

### ISSUE THREAD

**Issue by phoebosys** [scylladb/seastar#824] opened 2020-11-03 11:31 UTC
Forget my poor english please.

line 50: lowres_clock::time_point _earliest_started;
should be initial to max value, such as: lowres_clock::time_point _earliest_started{lowres_clock::duration::max()};
otherwise in : if (_earliest_started > started)
                         _earliest_started = started;
cause the val started always equals epoch time.

**Comment by tchaikov** [comment] 2022-12-27 07:12
this issue duplicates #803, which has been fixed by ef90a50cb3c227b1bfd0faa8e5cb693df730754f.

so this issue should be closed.

**Comment by avikivity** [comment] 2022-12-28 09:02
Closing as duplicate of #803.

**Closed by avikivity** 2022-12-28 09:02 UTC
