### ISSUE TITLE
rpc/rpc.cc - static assertion failed: Types must be no-throw move constructible

### ISSUE THREAD

**Issue by salesiss** [scylladb/seastar#288] opened 2017-05-21 22:57 UTC
while building seastar on amazon ami ubuntu
compiler is g++ (Ubuntu 5.4.1-2ubuntu1~14.04) 5.4.1 20160904

here:

root@ip-10-0-0-186:/home/seastar#  _./configure.py --compiler=/usr/bin/g++-5_
Notice: -fsanitize=vptr is broken, disabling; some debug mode tests are bypassed.

root@ip-10-0-0-186:/home/seastar# _ninja -j1_
[1/301] CXX build/release/rpc/rpc.o
FAILED: /usr/bin/g++-5 -MD -MT build/release/rpc/rpc.o -MF build/release/rpc/rpc.o.d -O2 -I build/release/gen -I build/release/c-ares -std=gnu++1y -g  -Wall -Werror -Wno-error=deprecated-declarations -fvisibility=hidden -pthread -I. -U_FORTIFY_SOURCE  -Ifmt -DBOOST_TEST_DYN_LINK -Wno-overloaded-virtual -DFMT_HEADER_ONLY -DHAVE_XEN -DHAVE_HWLOC -DHAVE_NUMA -c -o build/release/rpc/rpc.o rpc/rpc.cc
In file included from rpc/rpc.hh:27:0,
                 from rpc/rpc.cc:1:
./core/future.hh: In instantiation of ‘struct seastar::future_state<seastar::rpc::rcv_buf>’:
./core/future.hh:697:24:   required from ‘class seastar::future<seastar::rpc::rcv_buf>’
rpc/rpc_impl.hh:725:51:   required from here
./core/future.hh:128:5: error: static assertion failed: Types must be no-throw move constructible
     static_assert(std::is_nothrow_move_constructible<std::tuple<T...>>::value,
     ^
./core/future.hh: In instantiation of ‘struct seastar::future_state<long int, std::experimental::fundamentals_v1::optional<seastar::rpc::rcv_buf> >’:
./core/future.hh:697:24:   required from ‘class seastar::future<long int, std::experimental::fundamentals_v1::optional<seastar::rpc::rcv_buf> >’
rpc/rpc_impl.hh:1016:86:   required from here
./core/future.hh:128:5: error: static assertion failed: Types must be no-throw move constructible
ninja: build stopped: subcommand failed.
root@ip-10-0-0-186:/home/seastar#

**Comment by tgrabiec** [comment] 2017-05-22 06:46
Duplicate of #207. 

@salesiss The problem is too old version of boost library. Upgrade to >= 1.55

**Closed by tgrabiec** 2017-05-22 06:46 UTC

**Comment by salesiss** [comment] 2017-05-22 16:49
worked ! on ubuntu 17.04 amazon ami.
_tks tgrabiec fast solution !_
