### ISSUE TITLE
How to use future  `get` or `wait` method?

### ISSUE THREAD

**Issue by tanguofu** [scylladb/seastar#456] opened 2018-05-29 08:43 UTC
From example: 
`
// include headers

seastar::future<> f1() {
    seastar::thread th([] {
        std::cout << "Hi.\n";
        for (int i = 1; i < 4; i++) {
            seastar::sleep(std::chrono::seconds(1)).get();
            std::cout << i << "\n";
        }
    });
    return do_with(std::move(th), [] (auto& th) {
        return th.join();
    });
}
int main(int argc, char** argv) {    
    seastar::app_template app;   
    app.run_deprecated(argc, argv, f1);
    return 0;
}`

but when i compile and run, get core dumped : 
seastar/core/future.hh:894: void seastar::future<T>::do_wait() [with T = {}]: Assertion `thread' failed.
Aborting on shard 0.
Backtrace:
  0x000000000049a9ce
  0x000000000049aac3
  0x000000000049ab95
  /lib/x86_64-linux-gnu/libpthread.so.0+0x000000000001138f
  /lib/x86_64-linux-gnu/libc.so.6+0x0000000000035427
  /lib/x86_64-linux-gnu/libc.so.6+0x0000000000037029
  /lib/x86_64-linux-gnu/libc.so.6+0x000000000002dbd6
  /lib/x86_64-linux-gnu/libc.so.6+0x000000000002dc81
  0x000000000046f1ad
  0x0000000000464e6f
  0x000000000057f422
  0x0000000000497b56
  0x0000000000497e94
  0x00000000004ec967
  0x000000000057c155
  0x000000000045fee7
  /lib/x86_64-linux-gnu/libc.so.6+0x000000000002082f
  0x0000000000463b18
Aborted (core dumped)

my seastar build configure is:
  ./configure.py --compiler=/usr/bin/g++-7 --c-compiler=/usr/bin/gcc-7  --cflags="-fPIC"  --enable-dpdk  --enable-hwloc --c++-dialect=gnu++17 --mode=release
build os is :
  Ubuntu 16.04 
so how to use future in blocked mode? 

thanks

**Comment by nyh** [comment] 2018-05-29 09:09
This is a bug tracker, not a place for questions - those should be sent to the Seastar mailing list (seastar-dev on googlegroups.com). Please close this issue (unfortunately I don't have the permissions to do it myself).

But since I'm already here, I'll answer you: 
The code looks fine. The assertion failure suggests that a future's get() or wait() was called not inside a seastar::thread, but I don't see this in the code. I tried to compile your code, and it worked correctly - counting 1, 2, 3 in one second interval. And then it never exits - because you used run_deprecated(). You should use run() instead, then it exits after 3 seconds.
So I can't reproduce this crash.

**Comment by nyh** [comment] 2018-05-29 09:11
To clarify what I ran (and succeeded):
```c++
#include <core/future.hh>
#include <core/sleep.hh>
#include <core/thread.hh>
#include <core/app-template.hh>

seastar::future<> f1() {
seastar::thread th([] {
std::cout << "Hi.\n";
for (int i = 1; i < 4; i++) {
seastar::sleep(std::chrono::seconds(1)).get();
std::cout << i << "\n";
}
});
return do_with(std::move(th), [] (auto& th) {
return th.join();
});
}
int main(int argc, char** argv) {
seastar::app_template app;
//app.run_deprecated(argc, argv, f1);    // this works too, but then never exits after the counting is done
app.run(argc, argv, f1);
return 0;
}
```
```
c++ `pkg-config --cflags --libs ../../build/release/seastar.pc` try.cc
```

**Closed** 2018-05-29 09:11 UTC

**Comment by tanguofu** [comment] 2018-05-30 09:54
thanks to @nyh, the examples works;
  `wait` and `get` was  called in  seastar::thread works ok, but when not in   seastar::thread, just a  single `seastar::future<> f`  with app.run, how can i wait the `f` done ?

**Comment by nyh** [comment] 2018-05-30 10:28
@tanguofu please follow my advice and continue this thread on the mailing list, not on the bug tracker.

**Comment by MoFHeka** [comment] 2022-02-27 19:42
> thanks to @nyh, the examples works;
> `wait` and `get` was called in seastar::thread works ok, but when not in seastar::thread, just a single `seastar::future<> f` with app.run, how can i wait the `f` done ?

Hi, did you get the right method?
