### ISSUE TITLE
 1/47 Test  #1: Seastar.dist.consumer .........................***Failed   86.95 sec

### ISSUE THREAD

**Issue by closertotheheart** [scylladb/seastar#596] opened 2019-01-30 19:31 UTC
cloned today for the first time ... 2f3573178e7268f36d21ecdf09b4a83e22665579

```
:~/repos/seastar/build/release$ cat /etc/issue
Ubuntu 18.04.1 LTS \n \l

model name      : Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz


~/repos/seastar$ ninja -C build/release test
ninja: Entering directory `build/release'
[0/1] Running tests...
Test project /home/mcoyle/repos/seastar/build/release
      Start  1: Seastar.dist.consumer
 1/47 Test  #1: Seastar.dist.consumer .........................***Failed   86.95 sec
      Start  2: Seastar.unit.abort_source
 2/47 Test  #2: Seastar.unit.abort_source .....................   Passed    1.34 sec
      Start  3: Seastar.unit.alloc
 3/47 Test  #3: Seastar.unit.alloc ............................   Passed    1.29 sec
      Start  4: Seastar.unit.allocator
 4/47 Test  #4: Seastar.unit.allocator ........................   Passed    5.08 sec
      Start  5: Seastar.unit.alien
 5/47 Test  #5: Seastar.unit.alien ............................   Passed    1.25 sec
      Start  6: Seastar.unit.checked_ptr
 6/47 Test  #6: Seastar.unit.checked_ptr ......................   Passed    0.04 sec
      Start  7: Seastar.unit.chunked_fifo
 7/47 Test  #7: Seastar.unit.chunked_fifo .....................   Passed    0.21 sec
      Start  8: Seastar.unit.circular_buffer
 8/47 Test  #8: Seastar.unit.circular_buffer ..................   Passed    0.06 sec
      Start  9: Seastar.unit.circular_buffer_fixed_capacity
 9/47 Test  #9: Seastar.unit.circular_buffer_fixed_capacity ...   Passed    1.39 sec
      Start 10: Seastar.unit.connect
10/47 Test #10: Seastar.unit.connect ..........................   Passed    1.22 sec
      Start 11: Seastar.unit.defer
11/47 Test #11: Seastar.unit.defer ............................   Passed    0.07 sec
      Start 12: Seastar.unit.directory
12/47 Test #12: Seastar.unit.directory ........................   Passed    1.16 sec
      Start 13: Seastar.unit.distributed
13/47 Test #13: Seastar.unit.distributed ......................   Passed    1.71 sec
      Start 14: Seastar.unit.dns
14/47 Test #14: Seastar.unit.dns ..............................   Passed    7.47 sec
      Start 15: Seastar.unit.execution_stage
15/47 Test #15: Seastar.unit.execution_stage ..................   Passed    1.24 sec
      Start 16: Seastar.unit.expiring_fifo
16/47 Test #16: Seastar.unit.expiring_fifo ....................   Passed    1.15 sec
      Start 17: Seastar.unit.fair_queue
17/47 Test #17: Seastar.unit.fair_queue .......................   Passed   26.55 sec
      Start 18: Seastar.unit.file_io
18/47 Test #18: Seastar.unit.file_io ..........................   Passed    3.97 sec
      Start 19: Seastar.unit.foreign_ptr
19/47 Test #19: Seastar.unit.foreign_ptr ......................   Passed    1.34 sec
      Start 20: Seastar.unit.fstream
20/47 Test #20: Seastar.unit.fstream ..........................   Passed    2.28 sec
      Start 21: Seastar.unit.futures
21/47 Test #21: Seastar.unit.futures ..........................   Passed    2.43 sec
      Start 22: Seastar.unit.httpd
22/47 Test #22: Seastar.unit.httpd ............................   Passed    4.63 sec
      Start 23: Seastar.unit.ipv6
23/47 Test #23: Seastar.unit.ipv6 .............................   Passed    1.17 sec
      Start 24: Seastar.unit.json_formatter
24/47 Test #24: Seastar.unit.json_formatter ...................   Passed    1.20 sec
      Start 25: Seastar.unit.lowres_clock
25/47 Test #25: Seastar.unit.lowres_clock .....................   Passed    1.38 sec
      Start 26: Seastar.unit.net_config
26/47 Test #26: Seastar.unit.net_config .......................   Passed    0.07 sec
      Start 27: Seastar.unit.noncopyable_function
27/47 Test #27: Seastar.unit.noncopyable_function .............   Passed    0.05 sec
      Start 28: Seastar.unit.output_stream
28/47 Test #28: Seastar.unit.output_stream ....................   Passed    1.16 sec
      Start 29: Seastar.unit.packet
29/47 Test #29: Seastar.unit.packet ...........................   Passed    0.07 sec
      Start 30: Seastar.unit.program_options
30/47 Test #30: Seastar.unit.program_options ..................   Passed    0.06 sec
      Start 31: Seastar.unit.queue
31/47 Test #31: Seastar.unit.queue ............................   Passed    1.20 sec
      Start 32: Seastar.unit.rpc
32/47 Test #32: Seastar.unit.rpc ..............................   Passed    1.42 sec
      Start 33: Seastar.unit.semaphore
33/47 Test #33: Seastar.unit.semaphore ........................   Passed    1.61 sec
      Start 34: Seastar.unit.shared_ptr
34/47 Test #34: Seastar.unit.shared_ptr .......................   Passed    0.07 sec
      Start 35: Seastar.unit.signal
35/47 Test #35: Seastar.unit.signal ...........................   Passed    1.20 sec
      Start 36: Seastar.unit.simple_stream
36/47 Test #36: Seastar.unit.simple_stream ....................   Passed    0.06 sec
      Start 37: Seastar.unit.smp
37/47 Test #37: Seastar.unit.smp ..............................   Passed    1.09 sec
      Start 38: Seastar.unit.sstring
38/47 Test #38: Seastar.unit.sstring ..........................   Passed    0.06 sec
      Start 39: Seastar.unit.stall_detector
39/47 Test #39: Seastar.unit.stall_detector ...................   Passed    3.39 sec
      Start 40: Seastar.unit.thread
40/47 Test #40: Seastar.unit.thread ...........................   Passed    1.68 sec
      Start 41: Seastar.unit.thread_context_switch
41/47 Test #41: Seastar.unit.thread_context_switch ............   Passed    6.18 sec
      Start 42: Seastar.unit.timer
42/47 Test #42: Seastar.unit.timer ............................   Passed    4.50 sec
      Start 43: Seastar.unit.tuple_utils
43/47 Test #43: Seastar.unit.tuple_utils ......................   Passed    0.07 sec
      Start 44: Seastar.unit.unwind
44/47 Test #44: Seastar.unit.unwind ...........................   Passed    0.06 sec
      Start 45: Seastar.unit.weak_ptr
45/47 Test #45: Seastar.unit.weak_ptr .........................   Passed    0.06 sec
      Start 46: Seastar.app.memcached.memcached
46/47 Test #46: Seastar.app.memcached.memcached ...............   Passed   38.90 sec
      Start 47: Seastar.app.memcached.ascii
47/47 Test #47: Seastar.app.memcached.ascii ...................   Passed    1.13 sec

98% tests passed, 1 tests failed out of 47

Total Test time (real) = 220.68 sec

The following tests FAILED:
          1 - Seastar.dist.consumer (Failed)
Errors while running CTest
FAILED: CMakeFiles/test.util
cd /home/mcoyle/repos/seastar/build/release && /usr/local/bin/ctest --force-new-ctest-process
ninja: build stopped: subcommand failed.
```

**Comment by closertotheheart** [comment] 2019-01-30 21:34
sweet.  thx so much!

**Comment by nyh** [comment] 2021-09-09 08:17
Closing this issue - it was already declared a duplicate of #590, which is closed.

**Closed by nyh** 2021-09-09 08:17 UTC
