### ISSUE TITLE
global lock: dl_load_write_lock @ dl_iterate_phdr()

### ISSUE THREAD

**Issue by todin** [scylladb/seastar#399] opened 2018-02-02 13:41 UTC
Hi People.

I'm struggling with performance hit caused by global lock when exceptions are in use.
https://github.com/scylladb/seastar/issues/73 shows You have (or had) to struggle with it as well.
I also see in Your code exceptions are used, thus my question is if You did somehow manage to overcome the the global lock?

regards

**Comment by dorlaor** [comment] 2018-02-02 14:12
@gleb-cloudius changed the gcclib behavior to scale exceptions. It requires ggc7

**Comment by todin** [comment] 2018-02-02 15:26
@dorlaor, thank You for pointing this out. do You mean the following patch?: https://groups.google.com/forum/#!topic/seastar-dev/RuK-OajeqHk

If Yes, then it looks like an additional  work has been done within seastar code for dl_load_write_lock workaround.

I mean the code under the flag (if disabled) NO_EXCEPTION_HACK.

Do I understand it correct?

**Comment by dorlaor** [comment] 2018-02-02 16:37
Gleb is the right person behind it but I believe this is it

**Comment by gleb-cloudius** [comment] 2018-02-04 08:09
On Fri, Feb 02, 2018 at 07:26:29AM -0800, todin wrote:
> @dorlaor, thank You for pointing this out. do You mean the following patch?: https://groups.google.com/forum/#!topic/seastar-dev/RuK-OajeqHk
> 
> If Yes, then it looks like an additional  work has been done within seastar code for dl_load_write_lock workaround.
> 
> I mean the code under the flag (if disabled) NO_EXCEPTION_HACK.
> 
> Do I understand it correct?
> 
There are two locks that are taken on exception path. One was eliminated
in gcc7 (by https://gcc.gnu.org/viewcvs/gcc?view=revision&revision=240193)
for another we have a local workaround protected by NO_EXCEPTION_HACK.
NO_EXCEPTION_HACK should not be set unless you try to compile libstdc++
or libgcc statically, so workaround should be enabled by default.
https://github.com/scylladb/seastar/commit/464f5e3ae43b366b05573018fc46321863bf2fae
has much more detailed explanation of the whole ordeal. Note that the
workaround assumes that no libraries are loaded dynamically after
application starts (it is possible to support that too, just requires
more coding).

--
			Gleb.

**Comment by todin** [comment] 2018-02-05 15:49
@dorlaor, @gleb-cloudius,

thank You for clarification

**Comment by gleb-cloudius** [comment] 2018-02-05 16:54
@todin are you using seastar library and having this problem or are you seing
it in some other C++ project unrelated to seastar?

--
			Gleb.

**Comment by nyh** [comment] 2018-02-12 13:28
Can we close this issue, as a duplicate of #73?

**Comment by avikivity** [comment] 2018-02-12 13:34
It's a question, not a bug. Questions should be discussed on the mailing list. Closing.

**Closed by avikivity** 2018-02-12 13:34 UTC
